apiVersion: v1
kind: ConfigMap
metadata:
  name: feworkflow-config
  namespace: sample-app-namespace-1751002736509
  labels:
    app.kubernetes.io/name: feworkflow
    kubernetes.azure.com/generator: devhub
data: