apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: feworkflow
  labels:
    app.kubernetes.io/name: feworkflow
    app.kubernetes.io/part-of: feworkflow-project
    kubernetes.azure.com/generator: devhub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: feworkflow
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80