apiVersion: v1
kind: Service
metadata:
  name: feworkflow
  namespace: sample-app-namespace-1751002736509
  labels:
    app.kubernetes.io/name: feworkflow
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: feworkflow
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000